Add Abstract to Documentation
PascalStalder/BDA_FS19-Dokumentation pull request #5
Opened 2019-06-04 10:52 UTC by PascalStalder

2019-06-04 12:44 UTC, KilnOfTheSecondFlame requested changes

2019-06-04 12:44 UTC, KilnOfTheSecondFlame commented on BDA_FS19_Projektdokumentation.tex
> +	Die stetig steigenden Ansprüche an Komfort und Energieeffizienz von Gebäuden führen dazu, dass moderne Gebäude sich ständig weiterentwickeln und intelligenter werden. Damit eine Gebäudesteuerung int
Es sollte ein System entwickelt werden, welches **a**utomatisch die Anzahl [...]

2019-06-04 12:44 UTC, KilnOfTheSecondFlame commented on BDA_FS19_Projektdokumentation.tex
> +	Die stetig steigenden Ansprüche an Komfort und Energieeffizienz von Gebäuden führen dazu, dass moderne Gebäude sich ständig weiterentwickeln und intelligenter werden. Damit eine Gebäudesteuerung int
Dabei soll besonderes Augenmerk auf Herausforderungen, die durch die Verwendung von Low Resolution Infrarotkameras auftreten, _gelegt werden_ und es sollen die Grenzen eines solchen Systems aufgezeigt werden.
Weil:
Dabei soll besonderes Augenmerk auf Herausforderungen, [...] , _gelegt werden_ und es sollen die Grenzen eines solchen Systems aufgezeigt werden.

Vorschlag:
Dabei soll besonderes Augenmerk auf Herausforderungen, die durch die Verwendung von Low Resolution Infrarotkameras auftreten, _gelegt werden_. Insbesondere sollen die Grenzen eines solchen Systems _eruiert und_ aufgezeigt werden.

2019-06-04 12:44 UTC, KilnOfTheSecondFlame commented on BDA_FS19_Projektdokumentation.tex
> +	Zur Umsetzung dieses Projekts wurden verschiedene Algorithmen und Methoden analysiert. Daraus wurden zwei Algorithmen ausgewählt. Zum einen ein Convolutional Neural Network und zum anderen eine Refe
eine Referenzimplementation ~, in Form~ einer Threshold-Methode.

Hast du nicht sowieso Implementationen beider Algorithmen?

2019-06-04 12:44 UTC, KilnOfTheSecondFlame commented on BDA_FS19_Projektdokumentation.tex
> +	Zur Umsetzung dieses Projekts wurden verschiedene Algorithmen und Methoden analysiert. Daraus wurden zwei Algorithmen ausgewählt. Zum einen ein Convolutional Neural Network und zum anderen eine Refe
Diese beiden Algorithmen wurden so **i**mplementiert, dass sie **p**arallel getestet ~werden~ und die Ergebnisse verglichen werden können.

2019-06-04 12:44 UTC, KilnOfTheSecondFlame commented on BDA_FS19_Projektdokumentation.tex
> +	Zur Umsetzung dieses Projekts wurden verschiedene Algorithmen und Methoden analysiert. Daraus wurden zwei Algorithmen ausgewählt. Zum einen ein Convolutional Neural Network und zum anderen eine Refe
Um das neuronale Netz zu trainieren wurde eine Datensammlung aufgebaut. ~, um ausreichend Daten zur Verfügung zu haben.~ -> Redundant?

2019-06-04 12:44 UTC, KilnOfTheSecondFlame commented on include/Realisierung.tex
> +Die rohen Infrarotbilder wurden als .npy \parencite{npyformat} Files gespeichert. Dies, weil die Pixelwerte der Bilder in Kelvin*10 sind, d.h. 2731 entspricht 0\degree C. Aus diesem Grund konnten sie
Die rohen Infrarotbilder wurden als _.npy-Dateien_ gespeichert _\parencite{npyformat} ._

2019-06-04 13:03 UTC, PascalStalder commented on BDA_FS19_Projektdokumentation.tex
> +	Zur Umsetzung dieses Projekts wurden verschiedene Algorithmen und Methoden analysiert. Daraus wurden zwei Algorithmen ausgewählt. Zum einen ein Convolutional Neural Network und zum anderen eine Refe
> eine Referenzimplementation ~, in Form~ einer Threshold-Methode.
> 
> Hast du nicht sowieso Implementationen beider Algorithmen?

was meinsch met dem? ^^' weg Referenzimplementation? wenn jo... gschiider Refernzmethode?

2019-06-04 15:53 UTC, KilnOfTheSecondFlame commented on BDA_FS19_Projektdokumentation.tex
> +	Zur Umsetzung dieses Projekts wurden verschiedene Algorithmen und Methoden analysiert. Daraus wurden zwei Algorithmen ausgewählt. Zum einen ein Convolutional Neural Network und zum anderen eine Refe
Aaaah, ja das macht mehr sinn. Die Referenzimplementation ist für mich eine Implementation zur Validierung von etwas (ergo CNN & Threshold).
Referenzmethode passt auf jeden Fall besser

2019-06-04 22:28 UTC, KilnOfTheSecondFlame requested changes

2019-06-04 22:28 UTC, KilnOfTheSecondFlame commented on BDA_FS19_Projektdokumentation.tex
> +	Zur Umsetzung dieses Projekts wurden verschiedene Algorithmen und Methoden analysiert. Daraus wurden zwei Algorithmen ausgewählt. Zum einen ein Convolutional Neural Network und zum anderen eine Refe
Zum einen ein Convolutional Neural Network und _zur Referenz ein_ Threshold basierten Algorithmus.

Sorry, habs nicht genau durchgedacht vorhin!

2019-06-05 07:57 UTC, KilnOfTheSecondFlame approved these changes

2019-06-05 07:58 UTC, merged