update state of the art
PascalStalder/BDA_FS19-Dokumentation pull request #9
Opened 2019-06-05 10:10 UTC by PascalStalder

2019-06-05 12:56 UTC, KilnOfTheSecondFlame requested changes

2019-06-05 12:56 UTC, KilnOfTheSecondFlame commented on include/Stand_der_Technik.tex
> +Es wurden einige Papers zu Objekterkennung im Infrarobereich die auf die Verwendung von \gls{SVM} aufbauen \parencite{suard2006pedestrian, bertozzi2003pedestrian, zhang2007pedestrian}. Diese sind lei
Paper -> Artikel
da aber um das Jahr 2011 bei _der Mehrzahl von_ Wettbewerben \gls{SVM}'s von [...]

2019-06-05 12:56 UTC, KilnOfTheSecondFlame commented on include/Stand_der_Technik.tex
> +Es wurden einige Papers zu Objekterkennung im Infrarobereich die auf die Verwendung von \gls{SVM} aufbauen \parencite{suard2006pedestrian, bertozzi2003pedestrian, zhang2007pedestrian}. Diese sind lei
Und bei den SVMs wäre Pouly wohl nicht einverstanden, es gibt einfach das richtige Werkzeug für das richtige Problem

2019-06-05 12:56 UTC, KilnOfTheSecondFlame commented on include/Stand_der_Technik.tex
> +Um mittels Hough-Transformationen Formen zu erkennen wird zuerst mit einem Kantenerkennungsalgorithmus, wie z.B. der Canny-Algorithmus, alle Kanten in einem Binärbild repräsentiert. Im nächsten Schri
Um mittels Hough-Transformationen Formen zu erkennen, wird zuerst mit einem Kantenerkennungsalgorithmus, wie zum Beispiel dem Canny-Algorithmus, alle Kanten in einem Binärbild ~repräsentiert~ _gefunden/markiert/erkannt_.

2019-06-05 12:56 UTC, KilnOfTheSecondFlame commented on include/Stand_der_Technik.tex
> +Weiter gibt es auch noch Methoden wie \gls{k-NN} oder \gls{SVM}. Diese werden aber immer weniger verwendet, da sie in nahezu jedem Anwendungsfall von neuronalen Netzen überholt wurden. \gls{k-NN} wer
\gls{k-NN} werden oft als _ersten simplen Kontrollversuch oder für einfache Problemstellungen_, sowie in Kombination mit anderen Methoden, verwendet.

2019-06-05 12:56 UTC, KilnOfTheSecondFlame commented on include/Stand_der_Technik.tex
> +Weiter gibt es auch noch Methoden wie \gls{k-NN} oder \gls{SVM}. Diese werden aber immer weniger verwendet, da sie in nahezu jedem Anwendungsfall von neuronalen Netzen überholt wurden. \gls{k-NN} wer
Bis die nötige Rechenleistung verfügbar war um **t**iefe CNNs zu trainieren.

2019-06-05 12:56 UTC, KilnOfTheSecondFlame commented on include/Stand_der_Technik.tex
> +Weiter gibt es auch noch Methoden wie \gls{k-NN} oder \gls{SVM}. Diese werden aber immer weniger verwendet, da sie in nahezu jedem Anwendungsfall von neuronalen Netzen überholt wurden. \gls{k-NN} wer
Seither gewannen in solchen **Challenges** fast ausschliesslich

2019-06-05 12:56 UTC, KilnOfTheSecondFlame commented on BAT.bib
> +@misc{Historyo5:online,
![grafik](https://user-images.githubusercontent.com/7289947/58957712-742b7400-87a1-11e9-9df9-70f9d7f3c42f.png)
 History of computer vision contests won by deep CNNs on GPUs
![grafik](https://user-images.githubusercontent.com/7289947/58957944-07fd4000-87a2-11e9-929d-34f106a38d0d.png)

...
year={2017},
month={03},
organization={{The Swiss AI Lab}},
...

2019-06-05 13:06 UTC, PascalStalder commented on include/Stand_der_Technik.tex
> +Es wurden einige Papers zu Objekterkennung im Infrarobereich die auf die Verwendung von \gls{SVM} aufbauen \parencite{suard2006pedestrian, bertozzi2003pedestrian, zhang2007pedestrian}. Diese sind lei
Müessti vllt sege *im Bereich der Objekterkennung nicht mehr als aktueller Stand der Technik.. *

2019-06-06 11:20 UTC, KilnOfTheSecondFlame approved these changes

2019-06-06 11:25 UTC, merged